FROM php:8.2-fpm

# Copy composer.lock and composer.json
COPY composer.lock composer.json startup.sh /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    libonig-dev \
    curl \
    libzip-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

COPY ./crontab /etc/cron.d/crontab

# Copy existing application directory permissions
COPY --chown=www:www . /var/www
COPY docker/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN composer install --ignore-platform-reqs

# Change current user to www
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000 80 8080

RUN chmod u+x,g+x startup.sh

ENTRYPOINT ["/bin/sh","./startup.sh"]